name: Integration Test

on:
  push:
    branches:
      - "*"
      - '*/*'
      - '**'
      - '!main'
  pull_request:
    branches:
      - "*"
      - '*/*'
      - '**'


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Add Secrets to .env.local
        run: |
          touch .env.local
          echo MYSQL_ROOT_PASSWORD=${{secrets.MYSQL_ROOT_PASSWORD}} > .env.local

      - name: Build Containers
        run: docker compose up -d
      
      - name: Run Tests
        run: |
          docker exec app_backend pytest
          docker exec app_frontend pnpm run test run
      
      - name: Shut Down Containers
        run: docker compose down